package Bookstore.entity;
// Generated May 26, 2017 8:16:08 PM by Hibernate Tools 4.3.1



/**
 * Boek generated by hbm2java
 */
public class Boek  implements java.io.Serializable {


     private Integer idboek;
     private String titel;
     private String auteur;
     private String isbn;
     private String uitgever;
     private String jaar;
     private String foto;

    public Boek() {
    }

    public Boek(String titel, String auteur, String isbn, String uitgever, String jaar, String foto) {
       this.titel = titel;
       this.auteur = auteur;
       this.isbn = isbn;
       this.uitgever = uitgever;
       this.jaar = jaar;
       this.foto = foto;
    }
   
    public Integer getIdboek() {
        return this.idboek;
    }
    
    public void setIdboek(Integer idboek) {
        this.idboek = idboek;
    }
    public String getTitel() {
        return this.titel;
    }
    
    public void setTitel(String titel) {
        this.titel = titel;
    }
    public String getAuteur() {
        return this.auteur;
    }
    
    public void setAuteur(String auteur) {
        this.auteur = auteur;
    }
    public String getIsbn() {
        return this.isbn;
    }
    
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }
    public String getUitgever() {
        return this.uitgever;
    }
    
    public void setUitgever(String uitgever) {
        this.uitgever = uitgever;
    }
    public String getJaar() {
        return this.jaar;
    }
    
    public void setJaar(String jaar) {
        this.jaar = jaar;
    }
    public String getFoto() {
        return this.foto;
    }
    
    public void setFoto(String foto) {
        this.foto = foto;
    }




}


